"""Add children and growth records tables

Revision ID: a442250753cc
Revises: cbe94b687f55
Create Date: 2025-09-10 15:24:29.386839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a442250753cc'
down_revision = 'cbe94b687f55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sexenum'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('growth_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('age_months', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('muac_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('diet_diversity_score', sa.Integer(), nullable=False),
    sa.Column('recent_infection', sa.Boolean(), nullable=False),
    sa.Column('z_scores_percentiles', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_growth_records_age', 'growth_records', ['age_months'], unique=False)
    op.create_index('idx_growth_records_child_recorded', 'growth_records', ['child_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_growth_records_child_id'), 'growth_records', ['child_id'], unique=False)
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_index(op.f('ix_growth_records_child_id'), table_name='growth_records')
    op.drop_index('idx_growth_records_child_recorded', table_name='growth_records')
    op.drop_index('idx_growth_records_age', table_name='growth_records')
    op.drop_table('growth_records')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    # ### end Alembic commands ###
